@token = {{token}}
@host = localhost:5000

### Obtener todas las áreas
GET /api/areas HTTP/1.1
Host: {{host}}
Authorization: Bearer {{token}}

### Obtener área por ID
GET /api/areas/1 HTTP/1.1
Host: {{host}}
Authorization: Bearer {{token}}

### Crear área
POST /api/areas HTTP/1.1
Host: {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2,
  "nombre": "Plomería",
  "descripcion": "Servicios de plomería"
}

### Actualizar área
PUT /api/areas/1 HTTP/1.1
Host: {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Electricidad actualizada",
  "descripcion": "Servicios eléctricos y electrónicos"
}

### Eliminar área
DELETE /api/areas/1 HTTP/1.1
Host: {{host}}
Authorization: Bearer {{token}}
