@host = {{$dotenv %host}}
@token = {{$dotenv %token}}


GET / HTTP/1.1
Host: {{host}}
###
POST /api/auth/login HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "1234"
}

###
POST /api/auth/register HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "testpassword",
  "rol": "cliente"
}
###
POST /api/auth/register HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "admin2@test.com",
  "password": "1234",
  "rol": "admin"
}


###
POST /api/auth/login HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "cliente@test.com",
  "password": "1234"
}


###
GET /api/usuarios/1 HTTP/1.1
Host: {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}
